"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# APP = ['BatchConversion/BaseWindow.py']
DATA_FILES = ['BatchConversion/real_CIELAB.xlsx', 'BatchConversion/style.css']
OPTIONS = {
    'packages': ['BatchConversion', 'pyforms', 'sklearn', 'openpyxl'],
    'argv_emulation': 1,
}
setup(
    app=['BatchConversion/BaseWindow.py'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'], install_requires=['scikit-learn']
)
